// <auto-generated />
using Forma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Forma.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190722102317_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Forma.Data.Model.KorisnikModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojUkucana");

                    b.Property<string>("Grad");

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.Property<string>("PostanskiBroj");

                    b.Property<string>("Prezime")
                        .IsRequired();

                    b.Property<string>("Ulica");

                    b.Property<string>("Upit")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Korisnici");
                });
#pragma warning restore 612, 618
        }
    }
}
